# Generated by Django 4.1.5 on 2023-04-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_name_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
