# Generated by Django 4.1.5 on 2023-04-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_jobdescription_portal_jobtitle_applicant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtitle',
            old_name='last_update',
            new_name='last_updated',
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='role',
            field=models.CharField(default='', max_length=250),
        ),
    ]
